### ISSUE TITLE
How can I disable djvu-html5 in my browser (Firefox 51)?

### ISSUE THREAD

**Issue by msjasinski** [mateusz-matela/djvu-html5#11]
I like to download whole djvu files (merged) which is possible only using DJVu Plugin Viewer. In some cases djvu-html5 loads too fast making it impossible to choose the other viewer. How can I change my viewer or set a default viewer?

**Comment by mateusz-matela** [comment]
What page are you using?

**Comment by msjasinski** [comment]
I don't remember what page I had trouble with two days ago (it was a site in Poznań I think. If I remember it I'll post it here). I finally found an option to choose reader on the left hand UI panel. Each site has a little different layout, which may be confusing.
Now I've answered your question; please answer mine.

**Comment by mateusz-matela** [comment]
> Now I've answered your question; please answer mine.

Hmm, you make it sound like I owe you something now. My question indicated that you didn't give me enough information to let me help you, not that I was curious to know. And "I don't remember" is not a very helpful answer in that regard, is it?

First you ask:
> How can I change my viewer or set a default viewer?

Then you say:
> I finally found an option to choose reader on the left hand UI panel.

It seems you've solved your problem, so what kind of answer do you still expect from me?

**Comment by msjasinski** [comment]
I'm sorry if I offended you; I was talking out of frustration with my experience with DJVu, which could be better. I'm well aware that DJVu is a niche technology and it gets little media coverage, but it remains vital for Polish (or even European) humanists. The fact that one has to use outdated platforms to download whole publications because browser plugins are being phased out is one thing. Having to configure the browser every time, on each site, to choose the right reader also leads to frustration. So maybe there is some option in the mime-types or is it remembered in the cookies? DJVu-html5 is a great idea, but is does not have the download option - is it planned? Please treat my ticket as a means to ask for instruction / further information about the technology I depend on. 

All the best.

**Comment by mateusz-matela** [comment]
OK, so I guess we're talking about various instances of dLibra.

AFAIK there's no way to change viewing settings in all dLibras at once - each instance keeps this in its cookie, so if you use the viewer selection form and check the "Remember my choice" option, it should work for other objects in that library.

As for downloading directly from djvu-html5, it's problematic because the web-browser is not allowed to save multiple files at once. It's probably possible to save all files in a zip archive, but it's a lot of work and seemingly not much gain. There's already (usually) a download button in the left panel of dLibra's metadata page, which lets you save a zip archive.

**Comment by msjasinski** [comment]
Thanks for the clarification; now I know where I stand.

I agree with your position on a zip download. For now I'll continue to use my approach in downloading whole djvu files via legacy NPAPI-plugin.

This issue report may be closed.
