### ISSUE TITLE
JavaScript files not downloaded when repository cloned

### ISSUE THREAD

**Issue by beirnem** [mateusz-matela/djvu-html5#7]
There are two files missing when the repository is cloned:

Repos/djvu-html5/djvu-html5/war/djvu_html5/djvu_html5.nocache.js
Repos/djvu-html5/djvu-html5/war/djvu_html5/180E99CB20CC2E40C16924A6801C89F8.cache.js

The page does not work without these files.

**Comment by mateusz-matela** [comment]
There's no `.../war/djvu_html5` folder at all in the source repository, because it should be created during project compilation, along with the files you mentioned and several others.
Did you start the compilation? If so, in which way?
If you don't want to compile, just download a release package instead of cloning the repository.

**Comment by beirnem** [comment]
I didn't compile it, I just tried loading it in browser. I will try your suggestion.
